{
  unify.modules.sillytavern.nixos = {
    pkgs,
    lib,
    ...
  }: {
    virtualisation.oci-containers.containers."sillytavern" = {
      image = "ghcr.io/sillytavern/sillytavern:latest";
      environment = {
        "FORCE_COLOR" = "1";
        "NODE_ENV" = "production";
      };
      capabilities = {
        NET_ADMIN = true;
      };
      volumes = [
        "/home/teto/Services/SillyTavern/config:/home/node/app/config:rw"
        "/home/teto/Services/SillyTavern/data:/home/node/app/data:rw"
        "/home/teto/Services/SillyTavern/extensions:/home/node/app/public/scripts/extensions/third-party:rw"
        "/home/teto/Services/SillyTavern/plugins:/home/node/app/plugins:rw"
      ];
      ports = [
        "8000:8000/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--hostname=sillytavern"
        "--network-alias=sillytavern"
        "--network=sillytavern_default"
      ];
    };
    systemd.services."podman-sillytavern" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-sillytavern_default.service"
      ];
      requires = [
        "podman-network-sillytavern_default.service"
      ];
      partOf = [
        "podman-compose-sillytavern-root.target"
      ];
      wantedBy = [
        "podman-compose-sillytavern-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-sillytavern_default" = {
      path = [pkgs.podman];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f sillytavern_default";
      };
      script = ''
        podman network inspect sillytavern_default || podman network create sillytavern_default
      '';
      partOf = ["podman-compose-sillytavern-root.target"];
      wantedBy = ["podman-compose-sillytavern-root.target"];
    };

    # Builds
    systemd.services."podman-build-sillytavern" = {
      path = [pkgs.podman pkgs.git];
      serviceConfig = {
        Type = "oneshot";
        TimeoutSec = 300;
      };
      script = ''
        cd /home/teto
        podman build -t ghcr.io/sillytavern/sillytavern:latest .
      '';
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-sillytavern-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = ["multi-user.target"];
    };
  };
}
