# .sops.yaml

keys:
  - &oxce5 age12mcw2dvttthml53tvdc40uhka9fm753cj83lxumzaywjt4qdl3rs9m4agd
  - &teto age1xy4aata7jj4djkmw9s5lqcd43z34wnqqldayergls2u0an3ml3zss5xf5a
creation_rules:
  - path_regex: modules/secrets/[^/]+\.(yaml|json|env|ini|sops)$
    key_groups:
    - age:
      - *oxce5
      - *teto
